name: Test debug
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: 'in 1 hour'


permissions: {}

jobs:
  schedule:
    name: 📅 Schedule
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
